version: "3"
x-logging: &default-logging
    options:
        max-size: "1m"
        max-file: "3"
    driver: "json-file"

services:
    api-server:
        container_name: api-server
        image: api-server:latest
        restart: always
        build:
            dockerfile: Dockerfile
            context: ../backend
        links:
            - redis
        expose:
            - 3000
        volumes:
            - ../upload:/usr/src/app/upload
            - ../logs:/usr/src/app/logs
        logging: *default-logging

    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
    database:
        container_name: database
        image: mariadb:latest
        ports:
            - 3306:3306
        restart: always
        env_file: .env
        volumes:
            - ./mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
            - ./mariadb/var/lib/mysql:/var/lib/mysql
            - ./mariadb/var/log/maria:/var/log/maria
        environment:
            TZ: Asia/Seoul
        networks:
            - default
        command:
            [
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
            ]
    proxy:
        container_name: nginx_proxy
        restart: always
        image: nginx_proxy
        build:
            dockerfile: Dockerfile
            context: ./reverse-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./certbot/conf:/etc/nginx/ssl
            - ./certbot/data:/var/www/certbot
        logging: *default-logging

networks:
    default:
        external:
            name: web-services
